/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.miss.imissyou.mycar;

public final class Manifest {
    public static final class permission {
        /**  极光推送 
         */
        public static final String JPUSH_MESSAGE="com.miss.imissyou.mycar.permission.JPUSH_MESSAGE";
    }
}
